- name: Deploy AWX
  hosts: all
  become: true

  tasks:

    - name: sort out the yum repos
      yum:
        name: "{{ item }}"
        state: "latest"
      with_items:
        - "epel-release"
        - "yum-utils"

    - name: add the docker ce yum repo
      yum_repository:
        name: "docker-ce"
        description: "Docker CE YUM repo"
        gpgcheck: "yes"
        enabled: "yes"
        baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
        gpgkey: "https://download.docker.com/linux/centos/gpg"

    - name: install the prerequisites using yum
      yum:
        name: "{{ item }}"
        state: "latest"
      with_items:
        - "epel-release"
        - "libselinux-python"
        - "python-wheel"
        - "python-pip"
        - "git"
        - "docker-ce"

    - name: start and enable docker
      systemd:
        name: "docker"
        enabled: "yes"
        state: "started"

    - name: install the python packages using pip
      pip:
        name: "{{ item }}"
        state: "latest"
      with_items:
        - "pip"
        - "ansible"
        - "boto"
        - "boto3"
        - "docker"

    - name: check out the awx repo
      git:
        repo: "https://github.com/ansible/awx.git"
        dest: "~/awx"
        clone: "yes"
        update: "yes"

    - name: install awx
      command: "ansible-playbook -i inventory install.yml"
      args:
        chdir: "~/awx/installer"
      become_user: root
      become: yes
